version: '3'

services:
    dw:
        container_name: ${DW_HOST}
        build:
            context: .
            dockerfile: docker/postgres/Dockerfile
        environment:
            POSTGRES_DB: ${DW_DATABASE}
            POSTGRES_USER: ${DW_USER}
            POSTGRES_PASSWORD: ${DW_PASSWORD}
        volumes:
        - /var/lib/postgresql/data
        - ./docker/postgres/dumps:/docker-entrypoint-initdb.d
        ports:
            - "5434:5432"

    pgadmin4:
        container_name: ${PROJECT_NAME}_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "dw@unab.com"
            PGADMIN_DEFAULT_PASSWORD: "dw_pass"
        ports:
        - "81:80"
