version: '3'

services:
    api_db:
        container_name: ${PROJECT_NAME}_api_db
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3308:3306
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /var/lib/mysql

    symfony:
        container_name: ${PROJECT_NAME}_symfony
 #       restart: on-failure
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/


    api_nginx:
        container_name: ${PROJECT_NAME}_nginx
#        restart: on-failure
        depends_on: 
            - symfony 
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8080:80
