version: '3'

services:
    api_db:
        container_name: ${PROJECT_NAME}_api_db
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3308:3306
        volumes:
            - ./dumps/api:/docker-entrypoint-initdb.d
            - /var/lib/mysql

    symfony:
        container_name: ${PROJECT_NAME}_symfony
 #       restart: on-failure
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/


    api_nginx:
        container_name: ${PROJECT_NAME}_nginx
#        restart: on-failure
        depends_on: 
            - symfony 
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./symfony/:/var/www/symfony/
        ports:
            - 80:80

    pgadmin4:
        container_name: ${PROJECT_NAME}_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "dw@unab.com"
            PGADMIN_DEFAULT_PASSWORD: "dw_pass"
        ports:
        - "81:80"
