version: '3'

services:
    api_db:
        container_name: ${MYSQL_HOST}
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3308:3306
        volumes:
            - ./docker/db/dumps:/docker-entrypoint-initdb.d
            - /var/lib/mysql

    symfony:
        container_name: ${PROJECT_NAME}_symfony
 #       restart: on-failure
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            DW_DATABASE: ${DW_DATABASE}
            DW_USER: ${DW_USER}
            DW_PASSWORD: ${DW_PASSWORD}
            DW_HOST: ${DW_HOST}
        volumes:
            - ./symfony/:/var/www/symfony/
            - .symfony.env.local:/var/www/symfony/.env.local


    api_nginx:
        container_name: ${PROJECT_NAME}_nginx
#        restart: on-failure
        depends_on: 
            - symfony 
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./symfony/:/var/www/symfony/
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    dw:
        container_name: ${DW_HOST}
        build:
            context: .
            dockerfile: docker/postgres/Dockerfile
        environment: 
            POSTGRES_DB: ${DW_DATABASE}
            POSTGRES_USER: ${DW_USER}
            POSTGRES_PASSWORD: ${DW_PASSWORD}
        volumes:
        - /var/lib/postgresql/data
        - ./docker/postgres/dumps:/docker-entrypoint-initdb.d
        ports:
            - "5434:5432"

    pgadmin4:
        container_name: ${PROJECT_NAME}_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "dw@unab.com"
            PGADMIN_DEFAULT_PASSWORD: "dw_pass"
        ports:
        - "81:80"
